### ISSUE TITLE
Removing UI layer

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-rest#1]
Now we have an Angular front-end in an external project: https://github.com/spring-petclinic/spring-petclinic-angular2  (great job @vfedoriv ), we could plan to remove the UI layer of this project? Thus we will have a full back-end project.

**Comment by vfedoriv** [comment]
I think, yes.
P.S.
This Angular front-end should be improved (everyone's invited).

**Comment by arey** [comment]
We may also migrate to Spring Boot and be close to the canonical version maintained by Pivotal: https://github.com/spring-projects/spring-petclinic

**Comment by arey** [comment]
I've done the PR #2

**Comment by arey** [comment]
Merged
