### ISSUE TITLE
Inconsistencies in the API specification

### ISSUE THREAD

**Issue by apicarve** [spring-petclinic/spring-petclinic-rest#101]
Hello, we are building a research tool to generate API test suites and API specification automatically using UI test suites. When we compared the API specification we generate for your web app with the specification provided along with the web application, we found a few inconsistencies. Would you consider this to be a problem with the API specification or with the application?

Here are the API endpoints for which the server provided a 2xx or a 3xx status but the specification does not include them. Some of these endpoints are actually used by the UI to communicate with the server but not documented in the specification.

```			"/owners-options",
			"/owners/6-options",
			"/specialties-options",
			"/pets/{pet}-options",
			"/pets/{pet}-options",
			"/vets/3-options",
			"/pets-options",
			"/visits-options",
			"/owners/{id}-options",
			"/vets-options",
			"/petclinic/api/specialties/1-options",
			"/petclinic/api/pettypes/6-options",
			"/vets/{vet}-options",
			"/owners/{id}-options",
			"/vets/{vet}-options",
			"/visits/{visit}-options",
			"/pettypes-options"
```
For example `/pettypes-options` means that we tried the HTTP request `OPTIONS ` on the API endpoint `/pettypes` and received a status 200 from the server but there is no corresponding operation defined in the specification.

**Comment by arey** [comment]
OPTIONS requests are used by modern browers to send a preflight request and check the Cross-Origin Resource Policies (CORS). See https://www.baeldung.com/cs/cors-preflight-requests
The verb is for technical purpose and I don't think we have to describe it in an API specification.
