### ISSUE TITLE
Location header on specialties endpoint is wrong

### ISSUE THREAD

**Issue by stevenvanophem** [spring-petclinic/spring-petclinic-rest#102]
https://github.com/spring-petclinic/spring-petclinic-rest/blob/master/src/main/java/org/springframework/samples/petclinic/rest/controller/SpecialtyRestController.java#L80 describes the /specialties endpoint as /specialtys on the location header

**Comment by arey** [comment]
Thanks Steven for your feedback
It should be fixed with https://github.com/spring-petclinic/spring-petclinic-rest/pull/104
