### ISSUE TITLE
Add Vet endpoint does not work as described in the OpenAPI spec

### ISSUE THREAD

**Issue by stevenvanophem** [spring-petclinic/spring-petclinic-rest#103]
The OpenAPI spec describes the POST vet endpoint payload with the example

`
{
  "firstName": "James",
  "lastName": "Carter",
  "specialties": [
    {
      "name": "radiology"
    }
  ]
}
`

This does not work. The endpoint only works when also passing the id of an existing specialty.

I think the correct way to model the payload of this endpoint would be to pass a list of specialty ids, but that would break all the existing clients.

**Comment by arey** [comment]
By removing the `readOnly: true` from the `id` property of the `Specialty`, the Swagger UI is working.
This adds side effect on the  speciality API.
I don't know how to enhance the API design.

**Comment by alexandre-touret** [comment]
Hi,
It depends on if you want to avoid or not duplicate Specialty entries in your database.
You can remove the id in the DTO and always create new specialties...

I don't know about potential functional side effects w/ the duplication of these data

**Comment by arey** [comment]
I prefer to share the specialities between vets and don't duplicate this static data used in drop down list.

**Comment by alexandre-touret** [comment]
OK
I think, you should remove the IDs from the DTO and search for existing specialities before creating them during Vet Creation

**Comment by stevenvanophem** [comment]
Vet and Specialty are two different aggregates for the reason that you can register a specialty independent of a Vet. They should be linked by their ids in my opinion.

**Comment by arey** [comment]
See https://github.com/spring-petclinic/spring-petclinic-rest/issues/125
