### ISSUE TITLE
Getting 501 with Swagger

### ISSUE THREAD

**Issue by Ali-7CC** [spring-petclinic/spring-petclinic-rest#105]
Hey,

I'm trying to perform the following GET request

/api/owners/{ownerid}/pets/{petid}

The endpoint is documented in the openapi spec, but I get a 501 response code. I'm wondering whether the documentation is not up to date, or whether I'm missing something 😓 .

Thanks!

**Comment by alexandre-touret** [comment]
It needs to be implemented in the OwnerRestController

I can implement it
