### ISSUE TITLE
Datasource Property Isssue

### ISSUE THREAD

**Issue by sparun160782** [spring-petclinic/spring-petclinic-rest#12]
#-- This below line has to be commented out, not able to pick the driver class. The second line can be used
#spring.datasource.driverClassName=com.mysql.jdbc.Driver 
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

**Comment by vfedoriv** [comment]
It's funny, but real problem - additional spaces at the ends of strings.
You can select any line, or even two together - all variants work . But if presented any spaces between com.mysql.jdbc.Driver and carriage return - Spring cannot load Driver class.
