### ISSUE TITLE
Primary key in repository interface SpringDataUserRepository

### ISSUE THREAD

**Issue by julioapm** [spring-petclinic/spring-petclinic-rest#131]
When compiling the latest version in Spring STS IDE, an error is shown in interface:

@Profile("spring-data-jpa")
public interface SpringDataUserRepository extends UserRepository, Repository<User, Integer>  {

}

User classe has a String as ID, but the interface is declared with Integer. Should it be String? As in:

@Profile("spring-data-jpa")
public interface SpringDataUserRepository extends UserRepository, Repository<User, String>  {

}

**Comment by arey** [comment]
You're right @julioapm 
Do you want to submit a Merge Request in order to fix this issue?
