### ISSUE TITLE
[MySQL] Uncompatible column types error while trying to run the app and validate schema

### ISSUE THREAD

**Issue by firasrg** [spring-petclinic/spring-petclinic-rest#141]
Im trying to deploy the app locally, with `mysql` and `spring-data-jpa` profiles. The _MySQL Configuration_ indicates 2 steps: 
1. download mysql or use docker image
2. Apply the SQL scripts whether through properties or manual SQL execution.

The problem is with step N° 2: I've tried by uncommenting the following properties: 
```properties
spring.sql.init.schema-locations=classpath*:db/mysql/initDB.sql
spring.sql.init.data-locations=classpath*:db/mysql/populateDB.sql
```
And got NO database created! So ive tried the 2nd approch : Execute SQL scripts manually. Now, when i run the app i want to be certain that schema and code are valid, so i put `spring.jpa.hibernate.ddl-auto` to `validate`:
```properties
spring.jpa.hibernate.ddl-auto=validate
```
And I get the following error: 

```shell
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [enabled] in table [users]; found [tinyint (Types#TINYINT)], but expecting [bit (Types#BOOLEAN)]
```

**Comment by arey** [comment]
Hi @firasrg 
Did you try with the `mysql:5.7.8` image? It's working on my laptop. I used to change the `spring.datasource.username=root` property
In the `application-mysql.properties` you have to also uncomment the line number 2:
```
spring.sql.init.mode=always
```

**Comment by firasrg** [comment]
Hello @arey ! AFAIK [mysql v5.7.* is dead](https://endoflife.date/mysql) and no more supported. Why we dont use Mysql v8 as the dependency does ?!

> In the application-mysql.properties you have to also uncomment the line number 2:

I tried that as well, but the SQL code is uncompatible with mysql version, i recommend to migrate to v8

**Comment by arey** [comment]
You're right. Ready for the upgrade?
https://github.com/spring-petclinic/spring-petclinic-rest/pull/142

**Comment by firasrg** [comment]
sure!

**Comment by arey** [comment]
Should be ok. I let you try.
