### ISSUE TITLE
Should we refactor entity retrieval methods to use a private helper method?

### ISSUE THREAD

**Issue by earlspilner** [spring-petclinic/spring-petclinic-rest#144]
I am considering refactoring our `ClinicServiceImpl` class to use a private helper method for retrieving entities by their IDs. Currently, each method that retrieves an entity by its ID includes repetitive code for handling exceptions and null checks.

**Proposed Change:**

I propose introducing a private method to handle the retrieval of entities by ID, which would help eliminate code duplication and improve maintainability. Here’s a basic outline of what this could look like:

```java
private <T> T findEntityById(Supplier<T> supplier) {
    try {
        return supplier.get();
    } catch (ObjectRetrievalFailureException | EmptyResultDataAccessException e) {
        // Ignore not found exceptions
        return null;
    }
}
```

**Example Usage:**

Take a look at how this would roll in the findVisitById method:

```java
@Override
@Transactional(readOnly = true)
public Visit findVisitById(int visitId) throws DataAccessException {
    return findEntityById(() -> visitRepository.findById(visitId));
}
```

Looking forward to your feedback!

**Comment by arey** [comment]
It looks like a great idea. Thanks @earlspilner
