### ISSUE TITLE
self-href urls are not proper in rest api

### ISSUE THREAD

**Issue by kuldeepsidhu88** [spring-petclinic/spring-petclinic-rest#17]
I was trying to run spring-petclinic-rest in my local. I was able to run and build properly. But when I hit the URL  http://localhost:9966/petclinic/ 
This shows me below response 

`
{
  "_links" : {
    "petTypes" : {
      "href" : "http://localhost:9966/petclinic/petTypes"
    },
    "vets" : {
      "href" : "http://localhost:9966/petclinic/vets"
    },
    "users" : {
      "href" : "http://localhost:9966/petclinic/users"
    },
    "visits" : {
      "href" : "http://localhost:9966/petclinic/visits"
    },
    "pets" : {
      "href" : "http://localhost:9966/petclinic/pets"
    },
    "specialties" : {
      "href" : "http://localhost:9966/petclinic/specialties"
    },
    "owners" : {
      "href" : "http://localhost:9966/petclinic/owners"
    },
    "profile" : {
      "href" : "http://localhost:9966/petclinic/profile"
    }
  }
}
`

Upon clicking vets link from above, I got below response -

`
{
  "firstName" : "Helena",
  "lastName" : "Leary",
  "_links" : {
	"self" : {
	  "href" : "http://localhost:9966/petclinic/vets/1"
	},
	"vet" : {
	  "href" : "http://localhost:9966/petclinic/vets/1"
	},
	"specialties" : {
	  "href" : "http://localhost:9966/petclinic/vets/1/specialties"
	}
  }
}
`

But when I click on the self href url- it end up in being GET method not supported exception.

Actual URL for getting vets by id is 
http://localhost:9966/petclinic/api/vets/1

In code I could not find where it is configured or from where these links are coming. 
Can someone suggest how to add api in self href urls.

**Comment by vfedoriv** [comment]
Yes, it problem - Swagger use basePath from
server.context-path=/petclinic/
in application.properties file
You can change it to
server.context-path=/petclinic/api/
But then need change pathes in REST controllers files:
from
@RequestMapping("/api/owners")
to
@RequestMapping("/owners")
etc...

Need think about it - maybe alternative solution possible.

**Comment by arey** [comment]
Not sure about my analyze.
The controller reached by the the URL ```http://localhost:9966/petclinic/``` is not a Swagger controller but the Spring Data Rest controller ```org.springframework.data.rest.webmvc.RepositoryController```
I suppose we are exposing the REST API both by Spring MVC + Swagger and by Spring Data Rest 
In the pom.xml, could we remove the  ```spring-boot-starter-data-rest``` dependency?

**Comment by vfedoriv** [comment]
You absolutely right (no idea why I added this dependency in pom ?).
We can remove this or declare Spring Data Rest _basePath_ in application.properties file as
spring.data.rest.basePath=/api

**Comment by arey** [comment]
Spring Data Rest exports Spring Data repositories as REST resources with HAL. It may not uses the @RestController. Thus we have 2 API in a single war. 
If you set ```spring.data.rest.basePath=/datarest```, at startup, you will see 2 endpoints for retrieving a pet by its ID:
 - ```/api/pets/{petId}],methods=[GET]```
 - ```{[/datarest/{repository}/{id}],methods=[GET]```
For my point of view, the Spring Petclinic Rest application could have a branch or a fork with Spring Data Rest.  And the ```swagger-ui.html``` should be the hompepage of the master branch.

**Comment by kuldeepsidhu88** [comment]
Yes. Agree. swagger-ui.html should be homepage. As of now it shows REST resources info on homepage at http://localhost:9966/petclinic/
People can get confused seeing the REST URLs and try to retrieve resources using those.
