### ISSUE TITLE
Add new vet invalid entries

### ISSUE THREAD

**Issue by celestebrant** [spring-petclinic/spring-petclinic-rest#18]
Adding a new veterinarian with an invalid name (both first name and surname) should not be accepted by the system, but the 'Save Vet' button allows the data to be added to the database.

For example, the following data should fail but does not;
First name: "f"
Last name: "l"
Type: <null>

**Comment by vfedorivCR** [comment]
Well, we don't have any limitation for vet names. As I understand, the name/surname can be one-letter :)

**Comment by vfedoriv** [comment]
Well, we don't have any limitation for vet names. As I understand, the name/surname can be one-letter :)

**Comment by arey** [comment]
@celestebrant, what 'Save Vet' button do you mean? The swagger one or the Angular one?

**Comment by celestebrant** [comment]
It was the Angular one.
