### ISSUE TITLE
Unparseable date for POST /api/pets

### ISSUE THREAD

**Issue by KristofVanKriekingen1337** [spring-petclinic/spring-petclinic-rest#20]
Hey,

http://localhost:9966/petclinic/swagger-ui.html#!/pet-rest-controller/addPetUsingPOST

At the swagger of POST /api/pets the following format for birthDate is noted:

`"birthDate": "2019-03-15T06:32:56.523Z"`

When I try to send a POST request to create a pet. I receive this error:

`{   
    "className": "org.springframework.http.converter.HttpMessageNotReadableException",   
    "exMessage": "Could not read document: java.text.ParseException: Unparseable date: \"2018-08-13T06:32:56.478Z\"; nested exception is java.io.IOException: java.text.ParseException: Unparseable date: \"2018-08-13T06:32:56.478Z\""
}`

I've tried the date above & to change the date to yyyy-mm-dd etc.. but it's unable to parse the date?

**Comment by KristofVanKriekingen1337** [comment]
I found the solution: the swagger documentation is wrong.
The format should be: yyyy/MM/dd  (yyyy-mm-dd won't work only with slashes " / " )

Could this be updated?

**Comment by arey** [comment]
Hi @KristofVanKriekingen1337 Thank you for your feedback. Coud you please submit a Pull Request for the update?

**Comment by vfedoriv** [comment]
@KristofVanKriekingen1337 , yes, unfortunately, date format hardcoded in custom serializers/deserializers:
`Format formatter = new SimpleDateFormat("yyyy/MM/dd");`
And for some reasons swagger don't parse date annotations
`@DateTimeFormat(pattern = "yyyy/MM/dd")`

**Comment by simrin051** [comment]
Hi @arey 
![image](https://user-images.githubusercontent.com/26873360/133252065-f94ead81-bbc3-4b3b-9a76-14a26b0bfc4f.png)

May i know whether this issue is solved. I am not clear with this issue. I could see Birth Date mentioned as
2010/09/07. Can you please brief me the issue.

**Comment by arey** [comment]
@simrin051 the application is working. Swagger UI do not recognize the `yyyy/MM/dd` pattern and provide sample data with a bad format `2019-03-15T06:32:56.523Z`.
I don't know what to do with this issue that is references in the thread #52. Migrate to the RFC-3339 used by the OpenAPI specification and break backward compatibility with the Angular frontend?

**Comment by bebs99** [comment]
any news on how to fix that?

**Comment by arey** [comment]
This issue should be solbed by PR https://github.com/spring-petclinic/spring-petclinic-rest/pull/75
The date format is OK:
![image](https://user-images.githubusercontent.com/838318/147764024-d9ef1a54-e10c-4856-9014-63dd1a617562.png)
The `type.id` is missing in the sample. I don't know why.
