### ISSUE TITLE
POST Owner doesn't create Pet nor Visits

### ISSUE THREAD

**Issue by KristofVanKriekingen1337** [spring-petclinic/spring-petclinic-rest#21]
I'm trying to POST a new "owner" with "pet" and "visit": http://localhost:9966/petclinic/swagger-ui.html#!/owner-rest-controller/addOwnerUsingPOST

This is the JSON Body I am sending:

```
{
  "address": "Fakestreet",
  "city": "Langdorp",
  "firstName": "Kristof",
  "id": 0,
  "lastName": "fakelastname",
  "pets": [
    {
      "birthDate": "2000-08-13T06:32:56.478Z",
      "id": 0,
      "name": "Darko",
      "owner": {},
      "type": {
        "id": 2,
        "name": "dog"
      },
      "visits": [
        {
          "date": "2019/03/15",
          "description": "Sick",
          "id": 0,
          "pet": {}
        }
      ]
    }
  ],
  "telephone": "016565758"
}
```

I'm expecting the response so the Owner has been created, pet and visit also. (just like described on the swagger) Only the response I receive is:

```
{
    "id": 16,
    "firstName": "Kristof",
    "lastName": "fakelastname",
    "address": "Fakestreet",
    "city": "Langdorp",
    "telephone": "016565758",
    "pets": []
}
```

I checked and it doesn't create the pet nor visit in the backend.

**Comment by vfedoriv** [comment]
Hi @KristofVanKriekingen1337 
Well, this endpoint shouldn't save child objects( pet etc..). If you want to improve it, need changes in JacksonCustomOwnerDeserializer and OwnerRestController.

**Comment by simrin051** [comment]
Hi @arey / @vfedoriv /@ KristofVanKriekingen1337

If i am not wrong should the UI be also changed to add Pets and Visits.

**Comment by vfedoriv** [comment]
Owner endpoint responsibility - to add an owner. We have other endpoints for add pets and visits.
There should be a reason to mix up this in one endpoint and I'm not sure it's a good idea to do this in this application.

**Comment by simrin051** [comment]
@vfedoriv / @arey

Can i take up this issue

**Comment by simrin051** [comment]
Hi @vfedoriv / @arey 

Can i take up this issue

**Comment by arey** [comment]
Following @vfedoriv previous response, I'm not sure this is an issue. Thus we may close it. @vfedoriv did you confirm?

**Comment by vfedoriv** [comment]
@arey yes, thanks
