### ISSUE TITLE
Migrate to Spring Boot

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-rest#3]
We may migrate to Spring Boot in order to be close to the canonical version maintained by Pivotal: https://github.com/spring-projects/spring-petclinic

**Comment by arey** [comment]
PR https://github.com/spring-petclinic/spring-petclinic-rest/pull/5

**Comment by vfedoriv** [comment]
Not sure about this... I propose just create spring-boot branch.

**Comment by arey** [comment]
With the exception of the spring-framework-petclinic repo witch maintains a legacy version, all Spring Petclinic forks are based on Spring Boot. According to the Spring Team, this is the primary way to design Spring applications.

The question is: what is the goal of this spring-petclinic-rest repo? 
Here some answers:
- Providing a backend API for full JS front-end
- Showing how to design RestController with Jackson
- Configuring the Swagger UI

You may complete the list.

We don't have to take a quick decision. A spring-boot branch could be a choice. But I think we have to focus on the REST API and stay as close as possible to the canonical version (https://github.com/spring-projects/spring-petclinic).

**Comment by vfedoriv** [comment]
From my point of view, petclinic is application for **education** of Spring framework. For **different parts** of Spring framework. SpringBoot and Spring Data JPA - only two parts in big Spring infrastructure. So, I dont see any advantages limit programmers education with only one variant Spring configurations and one variant data access.
For me, better variant - create application with many different realizations/building blocks and (ideally) different configuration methods and better documentation. And any developer, who interesting to learn Spring, can improve any part of this system or compare different realization to see pro and contra.
So, I not interested "stay as close as possible to the canonical version" - no profit.

**Comment by arey** [comment]
@vfedoriv I'm agree with you about the education role of Spring Petclinic for Spring developers. 
I would prefer that each forks has it's own goal (i.e. spring-petclinic-microservices for Spring Cloud usage, spring-framework-petclinic for Spring Framework configuration + 3 persistance implementations). But your point of view can be defended. You're the team leader. So you decide :-)

**Comment by vfedoriv** [comment]
Migration to Spring Boot almost completed (still one xml config file in tests).
