### ISSUE TITLE
Question: Creating a Pet JSON Request

### ISSUE THREAD

**Issue by MakamuEvans** [spring-petclinic/spring-petclinic-rest#42]
Hi,

Is there a way i can implement creating a pet by just passing owner_id and type id instead of passing full object?

something like:

`{
  "birthDate": "2021-02-03T11:33:26.029Z",
  "id": 0,
  "name": "string",
  "owner_id":0,
  "type_id": 0,
  "visits": [
    {
      "date": "yyyy/MM/dd",
      "description": "string",
      "id": 0
    }
  ]
}`

**Comment by ramazansakin** [comment]
Hi @MakamuEvans ,

Of course you can create a new api with parameters you need, also as I see that pet class fields
 are not mandatory.
