### ISSUE TITLE
Removing xxxExt and xxxExtOverride

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-rest#6]
I would like to know why is the reason of maintening both a OwnerRepository and a OwnerRepositoryExt interface? I suppose you didn't want to modify the original classes. But for a beginner, I found the persistance layer very complex. I think we could merge it. Don't you?

**Comment by vfedoriv** [comment]
Yes, you right, maintaining old and extended classes not actual now. I will try merge it next week.

**Comment by vfedoriv** [comment]
or if you have time now... :)

**Comment by arey** [comment]
My holidays are over and I don't have much time :-(

**Comment by vfedoriv** [comment]
Merged. https://github.com/spring-petclinic/spring-petclinic-rest/commit/d5512262860d5e9dde0860405fbdb60c1c860041

**Comment by arey** [comment]
The code is really easier to understand. Great job.
