### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by bebs99** [spring-petclinic/spring-petclinic-rest#60]
I'm trying to start the site using PetClinicApplication but the following error keep showing up

" Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Nov 18 04:46:40 BRT 2021
There was an unexpected error (type=Not Found, status=404). "

I've used "spring-framework-petclinic" before and didnt had this issue.

**Comment by bebs99** [comment]
the issue is with the RootRestController it's redirecting to "/swagger-ui.html" while I think it should be "/swagger-ui/ "

**Comment by arey** [comment]
Thanks for the feedback @bebs99 This error come from a recent upgrade. I've fixed it https://github.com/spring-petclinic/spring-petclinic-rest/pull/62

**Comment by arey** [comment]
It should be work now. I let you try.

**Comment by arey** [comment]
Please reopen if the fix doesn't work.

**Comment by bebs99** [comment]
sorry for the delay, it's working here.
