### ISSUE TITLE
petDto not working propely

### ISSUE THREAD

**Issue by bebs99** [spring-petclinic/spring-petclinic-rest#61]
petDto is creating the following body 
{
  "birthDate": "Mon Sep 06 21:00:00 UTC 2010",
  "name": "Leo",
  "type": {
    "name": "cat"
  },
  "typeId": 1
} 

with this the push operation is refused and the following message is returned ( that is after changing the date to the yyyy-MM-dd format ) 

 cache-control: no-cacheno-storemax-age=0must-revalidate  connection: close  content-length: 0  date: Sat20 Nov 2021 06:08:20 GMT  errors: [{"objectName":"petDto","fieldName":"id","fieldValue":"null","errorMessage":"not null"},{"objectName":"petDto","fieldName":"type.id","fieldValue":"null","errorMessage":"not null"}]  expires: 0  pragma: no-cache  vary: OriginAccess-Control-Request-MethodAccess-Control-Request-Headers  x-content-type-options: nosniff  x-frame-options: DENY  x-xss-protection: 1; mode=block

**Comment by arey** [comment]
With last version of the app, the following snippet is working:
```
POST Request URL: http://localhost:9966/petclinic/api/owners/1/pets
{name: "Pet test", birthDate: "2021-12-29", type: {name: "snake", id: 4}, id: 16, visits: []}
```

**Comment by arey** [comment]
Please reopen this issue if it persist
