### ISSUE TITLE
Any interest in spring-petclinic-rest-hateoas

### ISSUE THREAD

**Issue by corneil** [spring-petclinic/spring-petclinic-rest#64]
Would there be any interest in a version of this that adds HATEOAS support along with an Angular version?

**Comment by arey** [comment]
Hi @corneil. Why not. We already have an angular version based on this API: https://github.com/spring-petclinic/spring-petclinic-angular
Do you think we could improve both versions to add HATEOS support? What would be the impacts?

**Comment by corneil** [comment]
I thought that a decent sized sample project with an opinionated HATEOAS implementation would be useful.

We have `spring-petclinic-graphql` 
Obviously there could be one or more clients implemented as part of this exercise. I believe that simplicity in the client code is where there is a huge payoff that people don't realize.

**Comment by arey** [comment]
Hi Corneil. In my professional life, I have never seen HATEOS in action yet. It could be changed. If you interested by implementing a new sample, it could be great. I could create a dedicated repository named `spring-petclinic-rest-hateoas`.

**Comment by corneil** [comment]
Thanks I was definitely thinking of a new project with backend and may more
than one front-end.
