### ISSUE TITLE
Error on start: bean of type 'org.springframework.samples.petclinic.mapper.OwnerMapper' that could not be found. 

### ISSUE THREAD

**Issue by manojkumarbehera** [spring-petclinic/spring-petclinic-rest#65]
Getting this error on start the boot class
Parameter 1 of constructor in org.springframework.samples.petclinic.rest.OwnerRestController required a bean of type 'org.springframework.samples.petclinic.mapper.OwnerMapper' that could not be found.

**Comment by arey** [comment]
Hi @manojkumarbehera. How did you start the application? With the `mvn spring-boot:run` command line or from your IDE?
In your IDE, the `mapstruct-processor` annotation processor should be enable.

**Comment by arey** [comment]
Do you have any feedback @manojkumarbehera ?
