### ISSUE TITLE
Complete the Petclinic OpenAPI spec

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-rest#69]
All REST endpoints of this Petclinic sample are not described into the [openapi.yml](https://github.com/spring-petclinic/spring-petclinic-rest/blob/master/src/main/resources/openapi.yml) spec file: POST `/vets`, PUT `/vets/{vetId}`, DELETE `/owners/{ownerId}` and so on.
This issue aims to complete it. Spring MVC controllers has not be updated in order to override methods that will be added to the generated interfaces (ie. `OwnersApi`, `VetsApi`)

**Comment by alexandre-touret** [comment]
Hi @arey , would you like I work on it ?

**Comment by arey** [comment]
Yes @alexandre-touret, you're welcome.
