### ISSUE TITLE
Can any one explain what CallMonitoringAspect.java does?

### ISSUE THREAD

**Issue by vikramsvk** [spring-petclinic/spring-petclinic-rest#8]
I am running JConsole,I am not able to see any attributes nor the @ManagedOperation reset() operation.

**Comment by vfedoriv** [comment]
It's legacy artifact - not sure can this really work now.
I think, need just remove this file from project (elegant solution, right ?).

**Comment by arey** [comment]
From my laptop, with JConsole, I can see the CallMonitor MBean and its reset() operation
<img width="894" alt="petclinic-jmx" src="https://user-images.githubusercontent.com/838318/32935855-358bfa86-cb72-11e7-9c97-bf778f79e783.png">
