### ISSUE TITLE
import org.springframework.samples.petclinic.rest.dto does not exist. Controller interfaces do not exist.

### ISSUE THREAD

**Issue by mangelo123** [spring-petclinic/spring-petclinic-rest#81]
I just downloaded the master branch. Build fails because the dto package does not exist. The controller interfaces also do not exist.

**Comment by mangelo123** [comment]
I Just discovered that they are all built dynamically by Maven. How can I add those to the sources in IntelliJ so that I don't see all of the compile errors?

**Comment by arey** [comment]
Hi @mangelo123 
DTOs are generated by MapStruct. Could you follow this instruction https://mapstruct.org/documentation/ide-support/ and please give us a feedback? Thus we could improve the readme.md or add some configuration in the pom.xml. Thanks

**Comment by alexandre-touret** [comment]
Hi @mangelo123 
Normally, after building the project, all the generated sources located in the ``target/generated-sources`` folder should appear as a source folder in your IDE.

**Comment by SushmithaGit** [comment]
hi,getting below error
java: package org.springframework.samples.petclinic.rest.dto does not exist
can you be more specific and elaborate a little more on what to do to get rid of this?

**Comment by alexandre-touret** [comment]
Hi,
This package and all the java classes source code belonging to it are generated during the build time.

You have to run this command first:

```
mvn clean install
```

**Comment by arey** [comment]
It is the second issue about MapStruct (see https://github.com/spring-petclinic/spring-petclinic-rest/issues/65). Maybe we should add some explanations to the readme?

**Comment by alexandre-touret** [comment]
@arey Yes. I will do that :)
