### ISSUE TITLE
Migrate to Spring Boot 3 and Java 17

### ISSUE THREAD

**Issue by stevenvanophem** [spring-petclinic/spring-petclinic-rest#83]
The maven build seems to run fine using Java 17. Migrating this build to Java 17 should be straightforward.

1. Update the Github workflow action to use Java 17
2. Add the property <java.version>17</java.version> to the maven properties

**Comment by alexandre-touret** [comment]
Hi @arey @stevenvanophem 
if it's not taken, I'll take care of it.

Tell me if you 're OK.

**Comment by arey** [comment]
Not sure that we have only to support Java 17 and above.
I prefer this sample remains compatible with the previous LTS (Java 11)

**Comment by alexandre-touret** [comment]
IMO, although the expected benefits will be weak, this sample should stick to the latest LTS ( --> 17)

**Comment by arey** [comment]
I propose to move to Java 17 with Spring Boot 3 migration.
