### ISSUE TITLE
Create pet endpoint

### ISSUE THREAD

**Issue by chrisbartoloburlo** [spring-petclinic/spring-petclinic-rest#86]
According to the open API spec, there is the following endpoint to create a pet: `http://localhost:9966/petclinic/api/pets`, however I am getting a `501` error whenever I send a POST request to that URL, indicating that it is not implemented. Is this the case?

**Comment by arey** [comment]
The `PetRestController` does not override the `addPet` method of the `PetsApi`. Thus the below code is executed:
```
return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
```

For creating a new pet, the Angular frontend use the  POST `/api/owners/{ownerId}/pets` endpoint:
```
curl 'http://localhost:9966/petclinic/api/owners/4/pets' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json' \
  --data-raw '{"id":null,"owner":{"firstName":"Harold","lastName":"Davis","address":"563 Friendly St.","city":"Windsor","telephone":"6085553198","id":4,"pets":[{"name":"Iggy","birthDate":"2010-11-30","type":{"name":"lizard","id":3},"id":5,"ownerId":4,"visits":[]}]},"name":"New Pet","birthDate":"2022-12-16","type":{"name":"lizard","id":3}}' \
```
We have to associate a pet with its owner. Thus I propose to remove the POST `/api/pets` endpoint. It's most easiest.

**Comment by alexandre-touret** [comment]
Hi @arey 
I can work on it if it's possible

Alexandre

**Comment by arey** [comment]
Hi @alexandre-touret  yes sure :)
