### ISSUE TITLE
Create PetType endpoint returns wrong PetType ID

### ISSUE THREAD

**Issue by chrisbartoloburlo** [spring-petclinic/spring-petclinic-rest#88]
When following the sequence of requests found in the following [shell script](https://github.com/spring-petclinic/spring-petclinic-rest/files/8425235/invalid_msg_7.sh.zip), the wrong PetType ID is returned upon creation.

Basically, the error occurs when one creates a pet type, deletes it, and creates it again. When creating it the second time, the ID returned in the response does not match the one actually given to the resource. This can be inspected by the performing a GET request on all pet types.

**Comment by davidecorradini** [comment]
UPDATE: According to the OpenAPI specification, the JSON request body for the POST request should not contain any ID. In practice, if an ID is not provided, the requests fails with status code 400. If an ID is provided, it will be printed back, although the actual ID might be different.

**Comment by breedx-splk** [comment]
Yeah, I believe that there are several APIs that are basically now in a bad/broken state -- you can't POST a new entity without an ID (you'll get a 400) and if you do supply an ID it will get created but the _actual_ id will be different (generated).

I did a couple experiments with removing the `id` field from some of the `required` blocks in the `openapi.yml` file, and that made several things much better....but ended up running into other problems with `POST /petclinic/api/pets` and couldn't get that working.

**Comment by arey** [comment]
I've checked the `/pettypes` api. The Swagger UI generates HTTP PUT and POST requests with no error.
The following POST curl command with no ID returns a generated ID.
```
$curl \
  --request POST \
  --url 'http://localhost:9966/petclinic/api/pettypes' \
  --header 'Content-Type: application/json' \
  --data '{"name":"Test"}' \    
  --location \
  --max-redirs 32
{"name":"Test","id":11}
```
In the openapi specification, the `readonly` property will generate the Swagger Schema AccessMode. It looks like not used by Spring MVC.
```
  @Min(0) 
  @Schema(name = "id", accessMode = Schema.AccessMode.READ_ONLY, example = "1", description = "The ID of the pet type.", required = false)
  public Integer getId() {
    return id;
  }
```
In the `PetTypeRestController`, we could add java test code that test if `id` is provided and generate an error `400`. I hope there is a more convenient way.
