### ISSUE TITLE
Request body of POST /pets

### ISSUE THREAD

**Issue by alainvanhout** [spring-petclinic/spring-petclinic-rest#9]
I am using spring-petclinic-rest as an example of a REST API. As a part of that, I am attempting to perform a POST request against /pets in order to create a new Pet record. It however seems that the 'id' field is required, with the associated behaviour that
- I can replace the contents of an existing pet via a POST to /pets (which does return a 201 instead of a 200)
- if I want to create an entirely new Pet record, I need to know which values for 'id' are not in use, rather than leave 'id' out and have an available value be assigned to it

**Comment by vfedoriv** [comment]
PetRestController use repository method save()
````
    public void save(Pet pet) {
        if (pet.getId() == null) {
            this.em.persist(pet);
        } else {
            this.em.merge(pet);
        }
    }
````
Why one method for insert and update ? Well, I think, it's historically and not best practices (SRP at the method level etc...)
But you not need " to know which values for 'id' are not in use" - just send JSON with { "id": null, ... }
and you create new pet and receive new id in response body.
