### ISSUE TITLE
The docker image is not updated on Dockerhub

### ISSUE THREAD

**Issue by mgalbis** [spring-petclinic/spring-petclinic-rest#93]
The latest version on Dockerhub is 2.1.5, but the latest version on this repository is 2.6.2. Could you update it?

Maybe it would be interesting if it were automatically deployed through a CI action.

**Comment by arey** [comment]
Hi Maria. You're right. The latest version is not published into Docker Hub. I did it that from my laptop. But you're right: it will be interesting to automatically deployed trough a GitHub Action. Did you have an experience?

**Comment by arey** [comment]
Hi @mgalbis 
Thank you for the remember. I've just published the `2.6.2` version into Docker Hub:
https://hub.docker.com/repository/docker/springcommunity/spring-petclinic-rest
![image](https://user-images.githubusercontent.com/838318/192133624-13401019-8169-4aed-aa3a-944b5bffd7ee.png)
I let you check
Regards
Antoine
